services:
  cache-server-9527:
    build: .
    container_name: cache-server-9527   
    ports:
      - "9527:9527"
    command: ["--port", "9527"]
    networks:
      - sdcnet

  cache-server-9528:
    build: .
    container_name: cache-server-9528
    ports:
      - "9528:9528"
    command: ["--port", "9528"]
    networks:
      - sdcnet

  cache-server-9529:
    build: .
    container_name: cache-server-9529
    ports:
      - "9529:9529"
    command: ["--port", "9529"]
    networks:
      - sdcnet

networks:
  sdcnet:
    driver: bridge